# Data Source Settings
spring:
  datasource:
    url: jdbc:h2:mem:jpademo
  sql:
    init:
      platform: h2
  jpa:
    show-sql: true
    hibernate.ddl-auto: create-drop

# http://localhost:8080/h2-console

# H2 Database Settings
spring.h2.console.enabled: true