mtr-service:
  host: 'rt.data.gov.hk'
  version: 'v1'
  endpoints:
    schedule: '/transport/mtr/getSchedule.php'

spring:
  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://postgres-container:5432/bootcamp_2508"
    username: "postgres"
    password: "admin1234"
  jpa:
    show-sql: false
    hibernate.ddl-auto: update
  data:
    redis:
      host: redis-container
      port: 6379
      database: 0
      timeout: 3000ms
