FROM openjdk:21
LABEL maintainer="itsupport@gmail.com"
ADD target/bc-mtr-station-0.0.1-SNAPSHOT.jar bc-mtr-station-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar","bc-mtr-station-0.0.1-SNAPSHOT.jar"]
EXPOSE 8080