FROM openjdk:21
LABEL maintainer="itsupport@gmail.com"
ADD target/demo-sb-calculator-0.0.1-SNAPSHOT.jar demo-sb-calculator-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar","demo-sb-calculator-0.0.1-SNAPSHOT.jar"]
EXPOSE 8092